FROM node:18-alpine

WORKDIR /app

COPY package*.json nest-cli.json tsconfig.json ./
# 2. 安装 pnpm
RUN npm install -g pnpm

# 3. 设置国内镜像（npm + pnpm）
ENV NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN pnpm config set registry https://registry.npmmirror.com

RUN pnpm install

COPY src ./src

RUN mkdir -p uploads

RUN npm run build

EXPOSE 3001

CMD ["node", "dist/main.js"]
